title: Emaad Qazi
description: Full Stack Developer  # Add a description
# logo: assets/img/logo.png  # Uncomment and add path if you have a logo
# show_downloads: true

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme

# Optional: Customize the theme
github:
  repository_name: "Emaad Qazi"
  repository_url: https://github.com/emaadqazi/emaadqazi.github.io
  
# Optional: Social links (if supported by theme)
author:
  name: Emaad Qazi
  email: qaziemaad@gmail.com
